name: DP Pull Request Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "SSH Connection Succesful"
    - name: Install Dependencies
      run: |
         cd dashboard && npm ci
    - name: Build Dashboard
      run: |
         cd dashboard && npm run build
    - name:  Copy Build to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key : ${{ secrets.SSH_PRIVATE_KEY }} 
        source: ./dashboard
        target: "projects/dc-pay"
        overwrite: true