name: DP Pull Request Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install Dependencies
      run: |
        cd dashboard && npm ci
        cd ../main-api && npm ci
    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "SSH Connection Succesful"
    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /projects/dc-pay/dashbaord
          git pull
          npm i && npm build