name: DP Pull Request Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "SSH Connection Succesful"
    - name: Pulling from Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd dc-pay 
    - name: Building on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd main-api/dc-pay && npm run build
    - name: Reload pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}   
        script: pm2 reload 0
      