# name: DP Pull Request Lint

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js 18.x
#       uses: actions/setup-node@v2
#       with:
#         node-version: '18.x'
#     - name: Test SSH Connection
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_IP_ADDRESS }}
#         username: ${{ secrets.SSH_USER_NAME }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           echo "SSH Connection Succesful"
    # - name: Pulling from Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     script: cd ${{ secrets.PROJECT_PATH }} && git pull origin main
    # - name: Compiling on Server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     script: cd ${{ secrets.PROJECT_PATH }}/api && npm run compile
    # - name: Reload pm2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}   
    #     script: pm2 reload 0
      